### ISSUE TITLE
Select a Framework for the architecture

### ISSUE THREAD

**Issue by t-lichtenstein** [BPChain/chainboard-prototype#2]

**Comment by fyndalf** [comment]
So far, the decision seems to be split between **Angular**, **React**, and **Vue**. As the project so far is only a prototype, some considerations should be made.

* Which framework is the easiest to pick up?
* Which framework is best for what we try to accomplish?
* Which framework is the best performance-wise?
* Which framework is the most flexible when we decide to change a lot of things?
* Which framework can be made to look fancy with the least amount of work?

After careful consideration, following conclusions have been drawn:
**React is the framework of our choice**, because it
* is the most flexible structurally and architecture-wise
* is able to work well with third-party libraries
* is easy to learn
* is good for highly interactive web apps
* is very stable, even when dealing with big data and computations
* has got an alright license
